language: ruby
rvm: 2.3.5
cache:
  bundler: true
before_install:
  - gem update --system
  - gem update bundler
  - gem install bundler-audit
script:
  - bundle exec rake spec
  - bundle-audit --update
notifications:
  email: false
